ShopDongHoMVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDongHoMVC.Data;
using ShopDongHoMVC.ViewModels;
using ShopDongHoMVC.Helpers;
using Microsoft.AspNetCore.Authorization;
using ShopDongHoMVC.Service;
using Microsoft.AspNetCore.Http;

namespace ShopDongHoMVC.Controllers
{
	public class CartController : Controller
	{
		private readonly IVnPayService _vnPayservice;
		private readonly DongHoShopMvcContext db;
		public CartController(DongHoShopMvcContext context, IVnPayService vnPayService)
		{
			_vnPayservice = vnPayService;
			db = context;
		}
		const string CART_KEY = "MYCART";
		public List<CartItemVM> Cart
		{
			get
			{
				return HttpContext.Session.Get<List<CartItemVM>>(CART_KEY) ?? new List<CartItemVM>();
			}
		}

		public IActionResult Index()
		{
			return View(Cart);
		}


		public IActionResult AddTocart(int id, int quantity = 1)
		{
		
			var cart = Cart;
			var item = cart.SingleOrDefault(p => p.MaSp == id);
			if (item == null)
			{
				var sanpham = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
				if (sanpham == null)
				{
					TempData["Message"] = $"Không tìm thấy hàng hóa có mã{id}";
					return Redirect("/404");
				}

				item = new CartItemVM
				{
					MaSp = sanpham.MaHh,
					TenSp = sanpham.TenHh,
					DonGia = sanpham.DonGia ?? 0,
					Hinh = sanpham.Hinh ?? string.Empty,
					SoLuong = quantity,
                    ThanhTien = (sanpham.DonGia ?? 0) * quantity

                };
				cart.Add(item);

			}
			else
			{
				item.SoLuong += quantity;
                item.ThanhTien = item.SoLuong * item.DonGia;


            }
			HttpContext.Session.Set(CART_KEY, cart);
			return RedirectToAction("Index");
		}

		public IActionResult RemoveCart(int id)
		{
			var cart = Cart;
			var item = cart.SingleOrDefault(p => p.MaSp == id);
			if (item != null)
			{
				cart.Remove(item);
				HttpContext.Session.Set(CART_KEY, cart);
			}

			return RedirectToAction("Index");
		}

        public IActionResult UpdateCart(int id, int quantity=1)
        {
            var cart = Cart;
            var item = cart.SingleOrDefault(p => p.MaSp == id);
            if (item != null)
            {
                if (quantity <= 0)
                {
                    cart.Remove(item);
                }
                else
                {
                    item.SoLuong = quantity;
					item.ThanhTien = item.DonGia * quantity;
                }

                HttpContext.Session.Set(CART_KEY, cart);
   

            }

            return RedirectToAction("Index");
        }




        [Authorize]
		[HttpGet]
		public IActionResult Checkout()
		{
			if (Cart.Count == 0)
			{
				return Redirect("/");
			}

			return View(Cart);
		}

		[Authorize]
		[HttpPost]
		public IActionResult Checkout(CheckoutVM model, string payment = "COD")
		{
			if (ModelState.IsValid)
			{
				if (payment == "Đặt hàng (VnPay)")
				{
					var vnPayModel = new VnPaymentRequestModel
					{
						Amount = Cart.Sum(p => p.ThanhTien),
						CreatedDate = DateTime.Now,
						Description = $"{model.HoTen} {model.DienThoai} {model.DiaChi}",
						FullName = model.HoTen,
						OrderId = new Random().Next(1000, 100000)
					};
					return Redirect(_vnPayservice.CreatePaymentUrl(HttpContext, vnPayModel));
				}

				var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID).Value;
				var khachHang = new KhachHang();
				if (model.GiongKhachHang)
				{
					khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
				}

				var hoadon = new HoaDon
				{
					MaKh = customerId,
					HoTen = model.HoTen ?? khachHang.HoTen,
					DiaChi = model.DiaChi ?? khachHang.DiaChi,
					DienThoai = model.DienThoai ?? khachHang.DienThoai,
					NgayDat = DateTime.Now,
					CachThanhToan = "COD",
					CachVanChuyen = "GRAB",
					MaTrangThai = 0,
					GhiChu = model.GhiChu
				};

				db.Database.BeginTransaction();
				try
				{

					db.Add(hoadon);
					db.SaveChanges();

					var cthds = new List<ChiTietHd>();
					foreach (var item in Cart)
					{
						cthds.Add(new ChiTietHd
						{
							MaHd = hoadon.MaHd,
							SoLuong = item.SoLuong,
							DonGia = item.DonGia,
							MaHh = item.MaSp,
							GiamGia = 0
						});
					}
					db.AddRange(cthds);
					db.SaveChanges();
					db.Database.CommitTransaction();

					HttpContext.Session.Set<List<CartItemVM>>(MySetting.CAT_KEY, new List<CartItemVM>());

					return View("Success");
				}
				catch
				{
					db.Database.RollbackTransaction();
				}
			}

			return View(Cart);
		}

		[Authorize]
		public IActionResult PaymentSuccess()
		{
			return View("Success");
		}

		[Authorize]
		public IActionResult PaymentFail()
		{
			return View();
		}
		public class DonHang
		{
			public string DienThoai { get; set; }
			// Các thuộc tính khác cần thiết
		}
		[Authorize]
		public IActionResult PaymentCallBack()
		{
			var response = _vnPayservice.PaymentExecute(Request.Query);

			if (response == null || response.VnPayResponseCode != "00")
			{
				TempData["Message"] = $"Lỗi thanh toán VN Pay: {response.VnPayResponseCode}";
				return RedirectToAction("PaymentFail");
			}

			try
			{
				// Lấy thông tin từ callback VNPay và lưu vào đơn hàng
				var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID).Value;
				var khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
				var hoadon = new HoaDon
				{
					MaKh = customerId,
					HoTen = khachHang?.HoTen ?? "", // Kiểm tra null trước khi sử dụng
					DiaChi = khachHang?.DiaChi ?? "",
					DienThoai = khachHang?.DienThoai ?? "",
					NgayDat = DateTime.Now,
					CachThanhToan = "VnPay",
					CachVanChuyen = "GRAB",
					MaTrangThai = 0,
					GhiChu = "" // Bạn có thể cung cấp ghi chú từ callback nếu cần
				};

				// Bắt đầu giao dịch
				using (var transaction = db.Database.BeginTransaction())
				{
					try
					{
						// Lưu đơn hàng vào cơ sở dữ liệu
						db.Add(hoadon);
						db.SaveChanges();

						// Lưu chi tiết hóa đơn vào cơ sở dữ liệu
						foreach (var item in Cart)
						{
							var chiTietHd = new ChiTietHd
							{
								MaHd = hoadon.MaHd,
								SoLuong = item.SoLuong,
								DonGia = item.DonGia,
								MaHh = item.MaSp,
								GiamGia = 0
							};
							db.Add(chiTietHd);
						}
						db.SaveChanges();

						// Commit giao dịch
						transaction.Commit();

						// Xóa giỏ hàng sau khi đã đặt hàng thành công
						HttpContext.Session.Set<List<CartItemVM>>(MySetting.CAT_KEY, new List<CartItemVM>());

						TempData["Message"] = $"Thanh toán VNPay thành công";
						return RedirectToAction("PaymentSuccess");
					}
					catch (Exception ex)
					{
						// Nếu có lỗi, rollback giao dịch
						transaction.Rollback();
						TempData["Message"] = $"Lỗi khi lưu đơn hàng: {ex.Message}";
						return RedirectToAction("PaymentFail");
					}
				}
			}
			catch (Exception ex)
			{
				TempData["Message"] = $"Lỗi khi xử lý thanh toán: {ex.Message}";
				return RedirectToAction("PaymentFail");
			}
		}
	}
}

ShopDongHoMVC/Controllers/HangHoaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopDongHoMVC.Data;
using ShopDongHoMVC.ViewModels;

namespace ShopDongHoMVC.Controllers
{
    public class HangHoaController : Controller
    {


        public readonly DongHoShopMvcContext db;
        public HangHoaController(DongHoShopMvcContext context)
        {
            db = context;
        }
        public IActionResult Index(int? loai)
        {

            var sanpham = db.HangHoas.AsQueryable();
            if (loai.HasValue) 
            {
                sanpham = sanpham.Where(p => p.MaLoai == loai.Value);
            }
            var result = sanpham.Select(p => new SanPhamVM
            {
                MaSp = p.MaHh,
                TenSp = p.TenHh,
                DonGia = p.DonGia ?? 0,
                HinhAnh = p.Hinh ?? "",
                MoTaNgan = p.MoTa ?? "",
                Tenloai = p.MaLoaiNavigation.TenLoai,
                SoLanXem = p.SoLanXem + 1
            }) ;
            
            
               
            return View(result);
        }


        public IActionResult Search(string? query)
        {
            var sanpham=db.HangHoas.AsQueryable();
            if (query != null)
            {
                sanpham = sanpham.Where(p => p.TenHh.Contains(query));
            }

            var result = sanpham.Select(p => new SanPhamVM
            {
                MaSp = p.MaHh,
                TenSp = p.TenHh,
                DonGia = p.DonGia ?? 0,
                HinhAnh = p.Hinh ?? "",
                MoTaNgan = p.MoTa ?? "",
                Tenloai = p.MaLoaiNavigation.TenLoai
            });

            return View(result);
        }

        public IActionResult Detail(int id) 
        {
            var item = db.HangHoas.Include(p=>p.MaLoaiNavigation).SingleOrDefault(x => x.MaHh == id);
            if (item == null) 
            {
                TempData["Messsage"] = $"Không thấy sản phẩm có mã {id}";
                return Redirect("/404");
            }
            var result = new ChiTietSanPhamVM
            {
                MaSp = item.MaHh,
                TenSp = item.TenHh,
                DonGia = item.DonGia ?? 0,
                HinhAnh= item.Hinh ?? string.Empty,
                ChiTiet = item.MoTa ?? string.Empty,
                MoTaNgan= item.MoTaDonVi ?? string.Empty,
                Tenloai= item.MaLoaiNavigation.TenLoai,
                SoLuongTon=10,
                DiemDanhGia = 5,
            };

            return View(result);

        }


       
      
    }
}

ShopDongHoMVC/Views/Cart/Checkout.cshtml
@model IEnumerable<ShopDongHoMVC.ViewModels.CartItemVM>
@{
	ViewData["Title"] = "Thanh Toán";
}
<div class="container-fluid page-header py-5">
	<h1 class="text-center text-white display-6">Thanh Toán</h1>
	<ol class="breadcrumb justify-content-center mb-0">
		<li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
		<li class="breadcrumb-item"><a href="#">Thành viên</a></li>
		<li class="breadcrumb-item"><a href="#">Đơn hàng</a></li>
		<li class="breadcrumb-item active text-white">Thanh Toán</li>
	</ol>
</div>
<div class="container-fluid py-5">
	<div class="container py-5">
		<h1 class="mb-4">Chi tiết đơn hàng</h1>
		<form asp-action="Checkout">
			<div class="row g-5">
				<form asp-action="Checkout" asp-controller="Cart">
					<div class="col-md-12 col-lg-6 col-xl-7">
						<div class="form-check my-3">
							<input type="checkbox" name="GiongKhachHang" class="form-check-input" id="GiongKhachHang" value="false">
							<label class="form-check-label" for="GiongKhachHang">Thông tin đặt hàng mặc định</label>
						</div>
						<div class="form-item delivery-info">
							<label class="form-label my-3">Người nhận hàng<sup>*</sup></label>
							<input type="text" name="HoTen" class="form-control">
						</div>
						<div class="form-item delivery-info">
							<label class="form-label my-3">Địa chỉ nhận hàng<sup>*</sup></label>
							<input type="text" name="DiaChi" class="form-control" placeholder="Hồ Chí Minh">
						</div>
						<div class="form-item delivery-info">
							<label class="form-label my-3">Điện thoại<sup>*</sup></label>
							<input type="text" name="DienThoai" class="form-control">
						</div>
						<div class="form-item mt-3">
							<textarea name="GhiChu" class="form-control" spellcheck="false" cols="30" rows="11" placeholder="Ghi chú"></textarea>
						</div>
						<input type="submit" name="payment" class="btn border-secondary text-uppercase text-primary w-100 mt-2" value="Đặt hàng (COD)">
						<input type="submit" name="payment" class="btn border-secondary text-uppercase text-primary w-100 mt-2" value="Đặt hàng (VnPay)">
						<input type="submit" name="payment" class="btn border-secondary text-uppercase text-primary w-100 mt-2" value="Đặt hàng (MoMo)">
					</div>
				</form>
				<div class="col-md-12 col-lg-6 col-xl-5">
					<div class="table-responsive">
						<table class="table">
							<thead>
								<tr>
									<th scope="col">Sản Phẩm</th>
									<th scope="col">Tên Sản Phẩm</th>
									<th scope="col">Giá</th>
									<th scope="col">Số Lượng</th>
									<th scope="col">Tổng Tiền</th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<th scope="row">
											<div class="d-flex align-items-center mt-2">
												<img src="~/Hinh/HangHoa/@item.Hinh" class="img-fluid rounded-circle" style="width: 90px; height: 90px;" alt="@item.TenSp">
											</div>
										</th>
										<td class="py-5">@item.TenSp</td>
										<td class="py-5">@item.DonGia VND</td>
										<td class="py-5">@item.SoLuong</td>
										<td class="py-5">@item.ThanhTien</td>
									</tr>
								}
								<tr>
									<th scope="row">
									</th>
									<td class="py-5"></td>
									<td class="py-5"></td>
									<td class="py-5">
										<p class="mb-0 text-dark py-3">Tổng: </p>
									</td>
									<td class="py-5">
										<div class="py-3 border-bottom border-top">
											<p class="mb-0 text-dark">@Model.Sum(p => p.ThanhTien).ToString("#,##0.00") VNĐ</p>
										</div>
									</td>
								</tr>
								@* <tr>
									<th scope="row">
									</th>
									<td class="py-5">
										<p class="mb-0 text-dark py-4">Shipping</p>
									</td>
									<td colspan="3" class="py-5">
										<div class="form-check text-start">
											<input type="checkbox" class="form-check-input bg-primary border-0" id="Shipping-1" name="Shipping-1" value="Shipping">
											<label class="form-check-label" for="Shipping-1">Free Shipping</label>
										</div>
										<div class="form-check text-start">
											<input type="checkbox" class="form-check-input bg-primary border-0" id="Shipping-2" name="Shipping-1" value="Shipping">
											<label class="form-check-label" for="Shipping-2">Flat rate: $15.00</label>
										</div>
										<div class="form-check text-start">
											<input type="checkbox" class="form-check-input bg-primary border-0" id="Shipping-3" name="Shipping-1" value="Shipping">
											<label class="form-check-label" for="Shipping-3">Local Pickup: $8.00</label>
										</div>
									</td>
								</tr> *@
								@* <tr>
									<th scope="row">
									</th>
									<td class="py-5">
										<p class="mb-0 text-dark text-uppercase py-3">TOTAL</p>
									</td>
									<td class="py-5"></td>
									<td class="py-5"></td>
									<td class="py-5">
										<div class="py-3 border-bottom border-top">
											<p class="mb-0 text-dark">$135.00</p>
										</div>
									</td *@>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
						<div class="col-12">
							<div class="form-check text-start my-3">
								<input type="checkbox" class="form-check-input bg-primary border-0" id="Transfer-1" name="Transfer" value="Transfer">
								<label class="form-check-label" for="Transfer-1">Chuyển khoản VNPAY hoặc MOMO </label>
							</div>
							<p class="text-start text-dark">Thực hiện thanh toán bằng phương thức chuyển khoản. Vui lòng ghi nội dung chuyển khoản là ID đơn hàng của bạn. Đơn đặt hàng của bạn sẽ không được vận chuyển cho đến khi chúng tôi nhận được thanh toán đúng với ID đơn hàng.</p>
						</div>
					</div>
					@* <div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
						<div class="col-12">
							<div class="form-check text-start my-3">
								<input type="checkbox" class="form-check-input bg-primary border-0" id="Payments-1" name="Payments" value="Payments">
								<label class="form-check-label" for="Payments-1">Check Payments</label>
							</div>
						</div>
					</div>
					<div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
						<div class="col-12">
							<div class="form-check text-start my-3">
								<input type="checkbox" class="form-check-input bg-primary border-0" id="Delivery-1" name="Delivery" value="Delivery">
								<label class="form-check-label" for="Delivery-1">Cash On Delivery</label>
							</div>
						</div>
					</div>
					<div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
						<div class="col-12">
							<div class="form-check text-start my-3">
								<input type="checkbox" class="form-check-input bg-primary border-0" id="Paypal-1" name="Paypal" value="Paypal">
								<label class="form-check-label" for="Paypal-1">Paypal</label>
							</div>
						</div>
					</div>
					<div class="row g-4 text-center align-items-center justify-content-center pt-4">
						<button type="button" class="btn border-secondary py-3 px-4 text-uppercase w-100 text-primary">Place Order</button>
					</div> *@
				</div>
			</div>
		</form>
	</div>
</div>
<!-- Checkout Page End -->
@section Scripts {
	<script>
		$(document).ready(function () {
			$("#GiongKhachHang").change(function () {
				if ($(this).prop("checked")) {
					$(this).val(true);
					$(".delivery-info").addClass("d-none");
				} else {
					$(this).val(false);
					$(".delivery-info").removeClass("d-none");
				}
			});
		});
	</script>
}

ShopDongHoMVC/Views/Cart/Index.cshtml
@model IEnumerable<ShopDongHoMVC.ViewModels.CartItemVM>
@{
    ViewData["Title"] = "Đơn Hàng";
}

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
    <h1 class="text-center display-6">Đơn Hàng</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
        <li class="breadcrumb-item"><a href="#">Thành viên</a></li>
        <li class="breadcrumb-item active">Đơn hàng</li>
    </ol>
</div>
<!-- Single Page Header End -->
<!-- Cart Page Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Sản phẩm</th>
                        <th scope="col">Tên sản phẩm</th>
                        <th scope="col">Giá </th>
                        <th scope="col">Số lượng</th>
                        <th scope="col">Thành tiền</th>
                        <th scope="col">Xử lí</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model){
                        <tr>
                            <th scope="row">
                                <div class="d-flex align-items-center">
                                    <img src="@item.Hinh" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                </div>
                            </th>
                            <td>
                                <p class="mb-0 mt-4">
                                    <a asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.MaSp">
                                        @item.TenSp
                                    </a>
                                </p>
                            </td>
                            <td>
                                <p class="mb-0 mt-4">@item.ThanhTien</p>
                            </td>
                            <td>
                                <div class="input-group quantity mt-4" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-minus rounded-circle bg-light border">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" class="form-control form-control-sm text-center border-0" value="@item.SoLuong">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-plus rounded-circle bg-light border">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="mb-0 mt-4">@item.ThanhTien</p>
                            </td>
                            <td>
                                <a asp-action="RemoveCart" asp-controller="Cart" asp-route-id="@item.MaSp" class="btn btn-md rounded-circle bg-light border mt-4">
                                    <i class="fa fa-times text-danger"></i>
                                </a>
                            </td>


                        </tr>
                    <td>
                        <button onclick="updateCart(@item.MaSp, @item.SoLuong)">Cập nhật</button>
                    </td>

                    }
                </tbody>
            </table>
            <a asp-action="Index" asp-controller="HangHoa">
                Tiếp tục mua hàng
            </a>
        </div>
        <div class="mt-5">
            <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Mã Khuyến mãi">
            <button class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="button">Áp dụng mã khuyến mãi</button>
        </div>
        <div class="row g-4 justify-content-end">
            <div class="col-8"></div>
            <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                <div class="bg-light rounded">
                    <div class="p-4">
                        <h1 class="display-6 mb-4">Tổng Đơn Hàng</span></h1>
                        <div class="d-flex justify-content-between mb-4">
                            <h5 class="mb-0 me-4">Tổng tiền:</h5>
                            <p class="mb-0">@Model.Sum(p => p.ThanhTien)</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-0 me-4">Shipping:</h5>
                            <div class="">
                                <p class="mb-0">30.000</p>
                            </div>
                        </div>
                        <p class="mb-0 text-end"></p>
                    </div>
                    <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                        <h5 class="mb-0 ps-4 me-4">Tổng hóa đơn</h5>
                        <p class="mb-0 pe-4">@Model.Sum(p => p.ThanhTien + 30000)</p>
                    </div>
                    <a class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" asp-action="Checkout" asp-controller="Cart">Xác nhận thanh toán</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function updateCart(productId, quantity) {
        fetch(`/Cart/UpdateCart?id=${productId}&quantity=${quantity}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error('Cập nhật giỏ hàng thất bại');
                }

                location.reload();
            })
            .catch(error => {
                console.error('Lỗi:', error);
            });
    }
</script>

ShopDongHoMVC/Views/Cart/PaymentFail.cshtml
@{
	ViewData["Title"] = "Payment Fail";
}

<div class="container-fluid contact py-5">
	<div class="container">
		<div class="p-5 bg-light rounded">
			<div class="row g-4">
				<div class="col-12">
					<div class="text-center mx-auto" style="max-width: 700px;">
						<h1 class="text-primary">Payment Fail</h1>
						<h3 class="text-danger">@TempData["Message"]</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

ShopDongHoMVC/Views/Cart/Success.cshtml
@{
	ViewData["Title"] = "Payment Success";
}

<div class="container-fluid contact py-5">
	<div class="container">
		<div class="p-5 bg-light rounded">
			<div class="row g-4">
				<div class="col-12">
					<div class="text-center mx-auto" style="max-width: 700px;">
						<h1 class="text-primary">Payment Success</h1>
						<h3 class="text-danger">@TempData["Message"]</h3>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>