ShopDongHoMVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using ShopDongHoMVC.Data;
using ShopDongHoMVC.ViewModels;
using ShopDongHoMVC.Helpers;
using Microsoft.AspNetCore.Authorization;
using ShopDongHoMVC.Service;
using Microsoft.AspNetCore.Http;

namespace ShopDongHoMVC.Controllers
{
	public class CartController : Controller
	{
		private readonly IVnPayService _vnPayservice;
		private readonly DongHoShopMvcContext db;
		public CartController(DongHoShopMvcContext context, IVnPayService vnPayService)
		{
			_vnPayservice = vnPayService;
			db = context;
		}
		const string CART_KEY = "MYCART";
		public List<CartItemVM> Cart
		{
			get
			{
				return HttpContext.Session.Get<List<CartItemVM>>(CART_KEY) ?? new List<CartItemVM>();
			}
		}

		public IActionResult Index()
		{
			return View(Cart);
		}


		public IActionResult AddTocart(int id, int quantity = 1)
		{
		
			var cart = Cart;
			var item = cart.SingleOrDefault(p => p.MaSp == id);
			if (item == null)
			{
				var sanpham = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
				if (sanpham == null)
				{
					TempData["Message"] = $"Không tìm thấy hàng hóa có mã{id}";
					return Redirect("/404");
				}

				item = new CartItemVM
				{
					MaSp = sanpham.MaHh,
					TenSp = sanpham.TenHh,
					DonGia = sanpham.DonGia ?? 0,
					Hinh = sanpham.Hinh ?? string.Empty,
					SoLuong = quantity,
                    ThanhTien = (sanpham.DonGia ?? 0) * quantity

                };
				cart.Add(item);

			}
			else
			{
				item.SoLuong += quantity;
                item.ThanhTien = item.SoLuong * item.DonGia;


            }
			HttpContext.Session.Set(CART_KEY, cart);
			return RedirectToAction("Index");
		}

		public IActionResult RemoveCart(int id)
		{
			var cart = Cart;
			var item = cart.SingleOrDefault(p => p.MaSp == id);
			if (item != null)
			{
				cart.Remove(item);
				HttpContext.Session.Set(CART_KEY, cart);
			}

			return RedirectToAction("Index");
		}

        public IActionResult UpdateCart(int id, int quantity=1)
        {
            var cart = Cart;
            var item = cart.SingleOrDefault(p => p.MaSp == id);
            if (item != null)
            {
                if (quantity <= 0)
                {
                    cart.Remove(item);
                }
                else
                {
                    item.SoLuong = quantity;
					item.ThanhTien = item.DonGia * quantity;
                }

                HttpContext.Session.Set(CART_KEY, cart);
   

            }

            return RedirectToAction("Index");
        }




        [Authorize]
		[HttpGet]
		public IActionResult Checkout()
		{
			if (Cart.Count == 0)
			{
				return Redirect("/");
			}

			return View(Cart);
		}

		[Authorize]
		[HttpPost]
		public IActionResult Checkout(CheckoutVM model, string payment = "COD")
		{
			if (ModelState.IsValid)
			{
				if (payment == "Đặt hàng (VnPay)")
				{
					var vnPayModel = new VnPaymentRequestModel
					{
						Amount = Cart.Sum(p => p.ThanhTien),
						CreatedDate = DateTime.Now,
						Description = $"{model.HoTen} {model.DienThoai} {model.DiaChi}",
						FullName = model.HoTen,
						OrderId = new Random().Next(1000, 100000)
					};
					return Redirect(_vnPayservice.CreatePaymentUrl(HttpContext, vnPayModel));
				}

				var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID).Value;
				var khachHang = new KhachHang();
				if (model.GiongKhachHang)
				{
					khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
				}

				var hoadon = new HoaDon
				{
					MaKh = customerId,
					HoTen = model.HoTen ?? khachHang.HoTen,
					DiaChi = model.DiaChi ?? khachHang.DiaChi,
					DienThoai = model.DienThoai ?? khachHang.DienThoai,
					NgayDat = DateTime.Now,
					CachThanhToan = "COD",
					CachVanChuyen = "GRAB",
					MaTrangThai = 0,
					GhiChu = model.GhiChu
				};

				db.Database.BeginTransaction();
				try
				{

					db.Add(hoadon);
					db.SaveChanges();

					var cthds = new List<ChiTietHd>();
					foreach (var item in Cart)
					{
						cthds.Add(new ChiTietHd
						{
							MaHd = hoadon.MaHd,
							SoLuong = item.SoLuong,
							DonGia = item.DonGia,
							MaHh = item.MaSp,
							GiamGia = 0
						});
					}
					db.AddRange(cthds);
					db.SaveChanges();
					db.Database.CommitTransaction();

					HttpContext.Session.Set<List<CartItemVM>>(MySetting.CAT_KEY, new List<CartItemVM>());

					return View("Success");
				}
				catch
				{
					db.Database.RollbackTransaction();
				}
			}

			return View(Cart);
		}

		[Authorize]
		public IActionResult PaymentSuccess()
		{
			return View("Success");
		}

		[Authorize]
		public IActionResult PaymentFail()
		{
			return View();
		}
		public class DonHang
		{
			public string DienThoai { get; set; }
			// Các thuộc tính khác cần thiết
		}
		[Authorize]
		public IActionResult PaymentCallBack()
		{
			var response = _vnPayservice.PaymentExecute(Request.Query);

			if (response == null || response.VnPayResponseCode != "00")
			{
				TempData["Message"] = $"Lỗi thanh toán VN Pay: {response.VnPayResponseCode}";
				return RedirectToAction("PaymentFail");
			}

			try
			{
				// Lấy thông tin từ callback VNPay và lưu vào đơn hàng
				var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID).Value;
				var khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
				var hoadon = new HoaDon
				{
					MaKh = customerId,
					HoTen = khachHang?.HoTen ?? "", // Kiểm tra null trước khi sử dụng
					DiaChi = khachHang?.DiaChi ?? "",
					DienThoai = khachHang?.DienThoai ?? "",
					NgayDat = DateTime.Now,
					CachThanhToan = "VnPay",
					CachVanChuyen = "GRAB",
					MaTrangThai = 0,
					GhiChu = "" // Bạn có thể cung cấp ghi chú từ callback nếu cần
				};

				// Bắt đầu giao dịch
				using (var transaction = db.Database.BeginTransaction())
				{
					try
					{
						// Lưu đơn hàng vào cơ sở dữ liệu
						db.Add(hoadon);
						db.SaveChanges();

						// Lưu chi tiết hóa đơn vào cơ sở dữ liệu
						foreach (var item in Cart)
						{
							var chiTietHd = new ChiTietHd
							{
								MaHd = hoadon.MaHd,
								SoLuong = item.SoLuong,
								DonGia = item.DonGia,
								MaHh = item.MaSp,
								GiamGia = 0
							};
							db.Add(chiTietHd);
						}
						db.SaveChanges();

						// Commit giao dịch
						transaction.Commit();

						// Xóa giỏ hàng sau khi đã đặt hàng thành công
						HttpContext.Session.Set<List<CartItemVM>>(MySetting.CAT_KEY, new List<CartItemVM>());

						TempData["Message"] = $"Thanh toán VNPay thành công";
						return RedirectToAction("PaymentSuccess");
					}
					catch (Exception ex)
					{
						// Nếu có lỗi, rollback giao dịch
						transaction.Rollback();
						TempData["Message"] = $"Lỗi khi lưu đơn hàng: {ex.Message}";
						return RedirectToAction("PaymentFail");
					}
				}
			}
			catch (Exception ex)
			{
				TempData["Message"] = $"Lỗi khi xử lý thanh toán: {ex.Message}";
				return RedirectToAction("PaymentFail");
			}
		}
	}
}

ShopDongHoMVC/Controllers/HangHoaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopDongHoMVC.Data;
using ShopDongHoMVC.ViewModels;

namespace ShopDongHoMVC.Controllers
{
    public class HangHoaController : Controller
    {


        public readonly DongHoShopMvcContext db;
        public HangHoaController(DongHoShopMvcContext context)
        {
            db = context;
        }
        public IActionResult Index(int? loai)
        {

            var sanpham = db.HangHoas.AsQueryable();
            if (loai.HasValue) 
            {
                sanpham = sanpham.Where(p => p.MaLoai == loai.Value);
            }
            var result = sanpham.Select(p => new SanPhamVM
            {
                MaSp = p.MaHh,
                TenSp = p.TenHh,
                DonGia = p.DonGia ?? 0,
                HinhAnh = p.Hinh ?? "",
                MoTaNgan = p.MoTa ?? "",
                Tenloai = p.MaLoaiNavigation.TenLoai,
                SoLanXem = p.SoLanXem + 1
            }) ;
            
            
               
            return View(result);
        }


        public IActionResult Search(string? query)
        {
            var sanpham=db.HangHoas.AsQueryable();
            if (query != null)
            {
                sanpham = sanpham.Where(p => p.TenHh.Contains(query));
            }

            var result = sanpham.Select(p => new SanPhamVM
            {
                MaSp = p.MaHh,
                TenSp = p.TenHh,
                DonGia = p.DonGia ?? 0,
                HinhAnh = p.Hinh ?? "",
                MoTaNgan = p.MoTa ?? "",
                Tenloai = p.MaLoaiNavigation.TenLoai
            });

            return View(result);
        }

        public IActionResult Detail(int id) 
        {
            var item = db.HangHoas.Include(p=>p.MaLoaiNavigation).SingleOrDefault(x => x.MaHh == id);
            if (item == null) 
            {
                TempData["Messsage"] = $"Không thấy sản phẩm có mã {id}";
                return Redirect("/404");
            }
            var result = new ChiTietSanPhamVM
            {
                MaSp = item.MaHh,
                TenSp = item.TenHh,
                DonGia = item.DonGia ?? 0,
                HinhAnh= item.Hinh ?? string.Empty,
                ChiTiet = item.MoTa ?? string.Empty,
                MoTaNgan= item.MoTaDonVi ?? string.Empty,
                Tenloai= item.MaLoaiNavigation.TenLoai,
                SoLuongTon=10,
                DiemDanhGia = 5,
            };

            return View(result);

        }


       
      
    }
}

ShopDongHoMVC/Controllers/KhachHangController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using ShopDongHoMVC.Data;
using ShopDongHoMVC.Helpers;
using ShopDongHoMVC.ViewModels;
using System.Security.Claims;
using System.Drawing;

namespace ShopDongHoMVC.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly DongHoShopMvcContext db;
        private readonly IMapper _mapper;

        public KhachHangController(DongHoShopMvcContext context, IMapper mapper)
        {
            db = context;
            _mapper = mapper;

        }

        #region Register
        [HttpGet]
        public IActionResult DangKy()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Dangky(RegisterVM model, IFormFile Hinh)
        {
            try
            { 
                if (ModelState.IsValid)
                {
                    var khachhang = _mapper.Map<KhachHang>(model);
                    khachhang.RandomKey = Util.GenerateRandomKey();
                    khachhang.MatKhau = model.MatKhau.ToMd5Hash(khachhang.RandomKey);
                    khachhang.HieuLuc = true;// sẽ cử lý khi dùng mail để active
                    khachhang.VaiTro = 0;

                    if (Hinh != null)
                    {
                        khachhang.Hinh = Util.UpLoadHinh(Hinh, "khachhang");
                    }
                    db.Add(khachhang);
                    db.SaveChanges();
                    return RedirectToAction("Index", "HangHoa");
                }
            }
            catch (Exception ex)
            {
                
            }
            return View();
        }

        #endregion

        public IActionResult QuenMatKhau() 
        {
            return View();
        }
        [HttpPost]

        public IActionResult QuenMatKhau(string email,string newpassword)
        {
            try 
            {
                var khachang = db.KhachHangs.SingleOrDefault(x => x.Email == email);
                if (khachang != null)
                {
                    if (string.IsNullOrEmpty(newpassword))
                    {
                        ModelState.AddModelError("newpassword", "Vui lòng nhập mật khẩu");
                        return View();
                    }

                    khachang.MatKhau = newpassword.ToMd5Hash(khachang.RandomKey);
                    db.SaveChanges();
                    ViewBag.SuccessMessage = "Mật khẩu mới đã được cập nhật thành công.";
                    return View("DangNhap");

                }
                else
                {
                    ModelState.AddModelError("email", "Email không tồn tại !");
                    return View();
                }
            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", "Đã xảy ra lỗi khi thực hiện yêu cầu đặt lại mật khẩu.");
                return View();
            }
        }

   
        #region Login
        [HttpGet]
        public IActionResult DangNhap(string? ReturnUrl)
        {Image quynhphuong=null;

            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
		public async Task<IActionResult> DangNhap(LoginVM model, string? ReturnUrl)
		{
			ViewBag.ReturnUrl = ReturnUrl;
			if (ModelState.IsValid)
			{
				var khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == model.UserName);
				if (khachHang == null)
				{
					ModelState.AddModelError("loi", "Không có khách hàng này");
				}
				else
				{
					if (!khachHang.HieuLuc)
					{
						ModelState.AddModelError("loi", "Tài khoản đã bị khóa. Vui lòng liên hệ Admin.");
					}
					else
					{
						if (khachHang.MatKhau != model.Password.ToMd5Hash(khachHang.RandomKey))
						{
							ModelState.AddModelError("loi", "Sai thông tin đăng nhập");
						}
						else
						{
							var claims = new List<Claim> {
						new Claim(ClaimTypes.Email, khachHang.Email),
						new Claim(ClaimTypes.Name, khachHang.HoTen),
						new Claim(MySetting.CLAIM_CUSTOMERID, khachHang.MaKh),
					};

							if (khachHang.VaiTro == 1)
							{
								claims.Add(new Claim(ClaimTypes.Role, "Admin"));
							}
							else if (khachHang.VaiTro == 0)
							{
								claims.Add(new Claim(ClaimTypes.Role, "Customer"));
							}

							var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
							var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

							await HttpContext.SignInAsync(claimsPrincipal);

							if (Url.IsLocalUrl(ReturnUrl))
							{
								return Redirect(ReturnUrl);
							}
							else
							{
								return Redirect("/");
							}
						}
					}
				}
			}
			return View();
		}
		#endregion

		[Authorize]
        public async Task<IActionResult> DangXuat()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }


        [Authorize]

        public IActionResult Profile()
        {
            var customerid = User.FindFirstValue(MySetting.CLAIM_CUSTOMERID);
            var khachhang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerid);
            if(khachhang == null) 
            {
                return NotFound();
            }

            return View(khachhang);
        }
    }
}

ShopDongHoMVC/Views/Shared/_DanhSachSanPham.cshtml
@{
    Layout = "_LayoutCustomer";
}

<!-- Single Page Header start -->
@RenderSection("BreadCum", required: false)

<!-- Single Page Header End -->
<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <div class="row g-4">
            <div class="col-lg-12">
                <div class="row g-4">
                    @* <div class="col-xl-3">
                    <div class="input-group w-100 mx-auto d-flex">
                    <form asp-action="Search" asp-controller="HangHoa">
                    <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1" name="query">
                    <button>
                    <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                    </button>
                    </form>
                    </div>
                    </div> *@
                    <div class="col-xl-12">
                        <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">
                            <label for="fruits">Default Sorting:</label>
                            <select id="fruits" name="fruitlist" class="border-0 form-select-sm bg-light me-3" form="fruitform">
                                <option value="volvo">Nothing</option>
                                <option value="saab">Popularity</option>
                                <option value="opel">Organic</option>
                                <option value="audi">Fantastic</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-lg-3">
                        <div class="row g-4">
                            <vc:menu-loai></vc:menu-loai>
                            <div class="col-lg-12">
                                <div class="mb-3">
                                    <h4 class="mb-2">Price</h4>
                                    <input type="range" class="form-range w-100" id="rangeInput" name="rangeInput" min="100000" max="500000000" value="0" oninput="amount.value=rangeInput.value">
                                    <output id="amount" name="amount" min-velue="100000" max-value="500000000" for="rangeInput">0</output>
                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="row g-4 justify-content-center">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fruits Shop End-->

ShopDongHoMVC/Views/Shared/_LayoutCustomer.cshtml
@* @model ShopDongHoMVC.Data.KhachHang *@
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <!-- Custom Styles -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">


    @RenderSection("Styles", required: false)
</head>
<body>
    <div>
        <!-- Navbar -->
        <div class="container-fluid fixed-top">
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a asp-action="Index" asp-controller="HangHoa" class="navbar-brand"><h1 class="text-primary display-6">THE GIOI DONG HO HOH</h1></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a asp-action="Index" asp-controller="HangHoa" class="nav-item nav-link active" style="margin-right: 10px">Trang chủ</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Thành viên</a>
                                <div class="dropdown-menu bg-secondary" aria-labelledby="navbarDropdown">
                                    <a asp-controller="Cart" asp-action="Index" class="dropdown-item">Đơn hàng</a>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        
                                        @* @if (Model.VaiTro == 1){
                                            <a asp-controller="Admin" asp-action="Index" class="dropdown-item">Admin Dashboard</a>
                                            <a asp-controller="KhachHang" asp-action="DangXuat" class="dropdown-item">Đăng xuất</a>
                                            <a asp-controller="KhachHang" asp-action="Profile" class="dropdown-item">Trang cá nhân</a>
                                        }
                                        else
                                        {
                                            <a asp-controller="KhachHang" asp-action="Profile" class="dropdown-item">Trang cá nhân</a>
                                            <a asp-controller="KhachHang" asp-action="DangXuat" class="dropdown-item">Đăng xuất</a>
                                        } *@
                                        <a asp-controller="Admin" asp-action="Index" class="dropdown-item">Admin Dashboard</a>
                                        <a asp-controller="KhachHang" asp-action="DangXuat" class="dropdown-item">Đăng xuất</a>
                                        <a asp-controller="KhachHang" asp-action="Profile" class="dropdown-item">Trang cá nhân</a>
                                        
                                    }
                                    else
                                    {
                                        <a asp-controller="KhachHang" asp-action="DangKy" class="dropdown-item">Đăng ký</a>
                                        <a asp-controller="KhachHang" asp-action="DangNhap" class="dropdown-item">Đăng nhập</a>
                                        <a asp-controller="KhachHang" asp-action="QuenMatKhau" class="dropdown-item">Quên mật khẩu</a>
                                    }
                                </div>
                            </div>
                            <a asp-action="Index" asp-controller="Home" class="nav-item nav-link active" style="margin-right: 10px">Liên Hệ</a>
                        </div>
                        <div class="d-flex m-3 me-0">
                            <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>

                            @await Component.InvokeAsync("Cart")

                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="KhachHang" asp-action="Profile" title="Xem thông tin người dùng" class="my-auto">
                                    <i class="fas fa-user fa-2x"></i>
                                </a>
                            }
                            else
                            {
                                <a asp-controller="KhachHang" asp-action="DangNhap" title="Đăng nhập nha" class="my-auto">
                                    <i class="fas fa-user fa-2x"></i>
                                </a>
                            }
                        </div>
                    </div>
                </nav>
            </div>
        </div>

        <!-- Modal Search -->
        <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <div class="input-group w-75 mx-auto d-flex">
                            <input id="searchText" type="search" class="form-control p-3" placeholder="keywords" aria-describedby="searchButton">
                            <button id="searchButton" class="btn btn-primary p-3"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div style="min-height: 400px;" class="hero-header">
            @RenderBody()
        </div>
        @await Html.PartialAsync("_Footer")
        @await Html.PartialAsync("_Copyright")
    </div>

    <!-- Back to Top Button -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>

    <!-- JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#searchButton").click(function () {
                let url = `/HangHoa/Search?query=` + $("#searchText").val();
                window.location.href = url;
            });
        });
    </script>

    @RenderSection("Scripts", required: false)

</body>
</html>

ShopDongHoMVC/Views/Shared/_LayoutFrame.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <!-- Custom Styles -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    @RenderSection("Styles", required: false)
</head>
<body>
    <div>
        @RenderBody() <!-- Corrected: Invoke RenderBody with parentheses -->
    </div>

    @RenderSection("Scripts", required: false) <!-- Render optional Scripts section -->
</body>
</html>